/* tslint:disable */
/* eslint-disable */
/**
 * ForestVPN Cloud API
 * ForestVPN Cloud - it's a Google Cloud but for VPN apps. Ready to use VPN Cloud Platform minimizes efforts to build fast, secure, and modern VPN apps. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@forestvpn.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Country } from './country';
/**
 * 
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    first_name?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    last_name?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    line1?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    line2?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    line3?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    line4?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    postcode?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    company?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    phone_number?: string;
    /**
     * 
     * @type {Country}
     * @memberof Account
     */
    country: Country;
    /**
     * 
     * @type {Date}
     * @memberof Account
     */
    created_at?: Date;
}
