/* tslint:disable */
/* eslint-disable */
/**
 * ForestVPN Cloud API
 * ForestVPN Cloud - it's a Google Cloud but for VPN apps. Ready to use VPN Cloud Platform minimizes efforts to build fast, secure, and modern VPN apps. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@forestvpn.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ResourceRef } from './resource-ref';
/**
 * 
 * @export
 * @interface Action
 */
export interface Action {
    /**
     * 
     * @type {string}
     * @memberof Action
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Action
     */
    command: string;
    /**
     * 
     * @type {Error}
     * @memberof Action
     */
    error?: Error;
    /**
     * 
     * @type {string}
     * @memberof Action
     */
    status: ActionStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof Action
     */
    progress: number;
    /**
     * 
     * @type {Array<ResourceRef>}
     * @memberof Action
     */
    resources: Array<ResourceRef>;
    /**
     * 
     * @type {Date}
     * @memberof Action
     */
    created_at: Date;
    /**
     * 
     * @type {Date}
     * @memberof Action
     */
    finished_at?: Date;
}

/**
    * @export
    * @enum {string}
    */
export enum ActionStatusEnum {
    Running = 'running',
    Failed = 'failed',
    Success = 'success'
}

