/* tslint:disable */
/* eslint-disable */
/**
 * ForestVPN Cloud API
 * ForestVPN Cloud - it's a Google Cloud but for VPN apps. Ready to use VPN Cloud Platform minimizes efforts to build fast, secure, and modern VPN apps. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@forestvpn.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Project } from './project';
import { User } from './user';
/**
 * 
 * @export
 * @interface Activity
 */
export interface Activity {
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    action_type?: string;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    resource_type: string;
    /**
     * 
     * @type {User}
     * @memberof Activity
     */
    user?: User;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    api_token?: string;
    /**
     * 
     * @type {Project}
     * @memberof Activity
     */
    project?: Project;
    /**
     * Source IP Address. Last 3 digits is hidden by security reason.
     * @type {string}
     * @memberof Activity
     */
    source_ip: string;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    status: ActivityStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof Activity
     */
    created_at: Date;
    /**
     * 
     * @type {Date}
     * @memberof Activity
     */
    finished_at?: Date;
}

/**
    * @export
    * @enum {string}
    */
export enum ActivityStatusEnum {
    Running = 'running',
    Failed = 'failed',
    Success = 'success'
}

