/* tslint:disable */
/* eslint-disable */
/**
 * ForestVPN Cloud API
 * ForestVPN Cloud - it's a Google Cloud but for VPN apps. Ready to use VPN Cloud Platform minimizes efforts to build fast, secure, and modern VPN apps. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@forestvpn.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Country } from './country';
import { PaymentProfile } from './payment-profile';
/**
 * 
 * @export
 * @interface Billing
 */
export interface Billing {
    /**
     * 
     * @type {string}
     * @memberof Billing
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Billing
     */
    name: string;
    /**
     * 
     * @type {Country}
     * @memberof Billing
     */
    country: Country;
    /**
     * 
     * @type {PaymentProfile}
     * @memberof Billing
     */
    payment_profile: PaymentProfile;
}
