/* tslint:disable */
/* eslint-disable */
/**
 * ForestVPN Cloud API
 * ForestVPN Cloud - it's a Google Cloud but for VPN apps. Ready to use VPN Cloud Platform minimizes efforts to build fast, secure, and modern VPN apps. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@forestvpn.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreateOrUpdatePaymentProfileRequest } from './create-or-update-payment-profile-request';
/**
 * 
 * @export
 * @interface CreateBillingRequest
 */
export interface CreateBillingRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateBillingRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBillingRequest
     */
    country: string;
    /**
     * 
     * @type {CreateOrUpdatePaymentProfileRequest}
     * @memberof CreateBillingRequest
     */
    payment_profile: CreateOrUpdatePaymentProfileRequest;
}
