/* tslint:disable */
/* eslint-disable */
/**
 * ForestVPN Cloud API
 * ForestVPN Cloud - it's a Google Cloud but for VPN apps. Ready to use VPN Cloud Platform minimizes efforts to build fast, secure, and modern VPN apps. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@forestvpn.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateOrUpdateBillingAccountRequest
 */
export interface CreateOrUpdateBillingAccountRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateBillingAccountRequest
     */
    first_name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateBillingAccountRequest
     */
    last_name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateBillingAccountRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateBillingAccountRequest
     */
    line1: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateBillingAccountRequest
     */
    line2?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateBillingAccountRequest
     */
    line3?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateBillingAccountRequest
     */
    line4?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateBillingAccountRequest
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateBillingAccountRequest
     */
    postcode: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateBillingAccountRequest
     */
    country: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateBillingAccountRequest
     */
    company: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateBillingAccountRequest
     */
    phone_number: string;
}
