/* tslint:disable */
/* eslint-disable */
/**
 * ForestVPN Cloud API
 * ForestVPN Cloud - it's a Google Cloud but for VPN apps. Ready to use VPN Cloud Platform minimizes efforts to build fast, secure, and modern VPN apps. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@forestvpn.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateOrUpdatePaymentProfileRequest
 */
export interface CreateOrUpdatePaymentProfileRequest {
    /**
     * In some situations, your tax status will determine your tax treatment.
     * @type {string}
     * @memberof CreateOrUpdatePaymentProfileRequest
     */
    tax_number?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdatePaymentProfileRequest
     */
    business_name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdatePaymentProfileRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdatePaymentProfileRequest
     */
    address_line1: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdatePaymentProfileRequest
     */
    address_line2?: string;
    /**
     * Administrative area. Usually it is city or region.
     * @type {string}
     * @memberof CreateOrUpdatePaymentProfileRequest
     */
    address_line3: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdatePaymentProfileRequest
     */
    primary_contact_name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdatePaymentProfileRequest
     */
    primary_contact_phone: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdatePaymentProfileRequest
     */
    primary_contact_email: string;
}
