/* tslint:disable */
/* eslint-disable */
/**
 * ForestVPN Cloud API
 * ForestVPN Cloud - it's a Google Cloud but for VPN apps. Ready to use VPN Cloud Platform minimizes efforts to build fast, secure, and modern VPN apps. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@forestvpn.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DataUsageLimit
 */
export interface DataUsageLimit {
    /**
     * 
     * @type {string}
     * @memberof DataUsageLimit
     */
    id: string;
    /**
     * Duration in ISO 8601 format. Example P7D - per week
     * @type {string}
     * @memberof DataUsageLimit
     */
    duration: string;
    /**
     * Value in bytes. For convert to MegaBytes use formula {value} / (1024 * 1024)
     * @type {number}
     * @memberof DataUsageLimit
     */
    value: number;
    /**
     * 
     * @type {string}
     * @memberof DataUsageLimit
     */
    scope: DataUsageLimitScopeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum DataUsageLimitScopeEnum {
    Global = 'global',
    Local = 'local'
}

