/* tslint:disable */
/* eslint-disable */
/**
 * ForestVPN Cloud API
 * ForestVPN Cloud - it's a Google Cloud but for VPN apps. Ready to use VPN Cloud Platform minimizes efforts to build fast, secure, and modern VPN apps. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@forestvpn.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
/**
 * 
 * @export
 * @interface PaymentProfile
 */
export interface PaymentProfile {
    /**
     * 
     * @type {string}
     * @memberof PaymentProfile
     */
    id?: string;
    /**
     * In some situations, your tax status will determine your tax treatment.
     * @type {string}
     * @memberof PaymentProfile
     */
    tax_number?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentProfile
     */
    business_name: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentProfile
     */
    name: string;
    /**
     * 
     * @type {Address}
     * @memberof PaymentProfile
     */
    address: Address;
    /**
     * 
     * @type {string}
     * @memberof PaymentProfile
     */
    primary_contact_name: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentProfile
     */
    primary_contact_phone: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentProfile
     */
    primary_contact_email: string;
}
