/* tslint:disable */
/* eslint-disable */
/**
 * ForestVPN Cloud API
 * ForestVPN Cloud - it's a Google Cloud but for VPN apps. Ready to use VPN Cloud Platform minimizes efforts to build fast, secure, and modern VPN apps. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@forestvpn.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Profile
 */
export interface Profile {
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    external_key: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    status: ProfileStatusEnum;
    /**
     * A secret key that should be used along with ID in ForestVPN Cloud VPN SDK.
     * @type {string}
     * @memberof Profile
     */
    secret_key: string;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to metadata. 
     * @type {{ [key: string]: string; }}
     * @memberof Profile
     */
    metadata: { [key: string]: string; };
}

/**
    * @export
    * @enum {string}
    */
export enum ProfileStatusEnum {
    Active = 'active',
    Suspended = 'suspended'
}

